### ISSUE TITLE
compile and run script

### ISSUE THREAD

**Issue by arademaker** [armedbear/abcl#189]
I wrote a simple lisp file that should be used as script. I learned that I can compile with `(cl-compile-file ...)` and produce the `.abcl` file. But how can I 'execute' this file?

**Comment by easye** [comment]
The results of compiling a file into one of type "abcl" is what is known as a fasl ("fast system loading").  Fasls are not directly executable under any Lisp, but must be loaded by the implementation. When you use ASDF to encapsulate your Lisp code, such compilation is handled automatically with the result cached in the appropriate XDG location (i.e. for unix  under ```<file:~/.cache/…```).

To make a script you have (at least) two routes:

1)  Create a script which invokes `abcl` to load and execute the file. 
```lisp
#!/usr/bin/env bash
abcl --batch --load path-to-file.abcl
```

2) Install Faré's excellent CL-LAUNCH <https://www.cliki.net/cl-launch>, which installs a small shim as `cl` which provides abstractions for common things that one wishes to do in a script such as accessing standard input, processing arguments, etc. Since CL-LAUNCH uses ASDF, the  compilation and caching will be handled for you automatically.

As an example, the following script will output information about the arguments it is invoked with:

```lisp
#!/usr/local/bin/cl --lisp abcl -E main 
(defun main (argv)
  (if argv
      (format *standard-output* "~{~a ~}~%")
      (format *standard-output* "No args~%")))
```

-- 

I would prefer to answer questions about ABCL on the mailing list <https://mailman.common-lisp.net/pipermail/armedbear-devel/>, whose freely redstributable contents will (hopefully) outlive that of an ephemeral commercial service like Github.  

Closing the issue as addressed, please re-open if something is unclear.
