### ISSUE TITLE
being the elements of

### ISSUE THREAD

**Issue by Slids** [armedbear/abcl#272]
I occasionally want to iterate over a sequence, but I don't know
if it's a list or a vector.
SBCL and CCL have me covered, just write
"being the elements of"
but ABCL can't do such a thing.

**Comment by alessiostalla** [comment]
Oh yes it can, you just need to (require :extensible-sequences)

**Comment by Slids** [comment]
Awesome, tank you.

**Comment by Slids** [comment]
Still sad it's another dep though

**Comment by alanruttenberg** [comment]
Mark, can't we set it to autoload?
Alan

**Comment by easye** [comment]
> Mark, can't we set it to autoload? Alan

Since EXTENSIBLE-SEQUENCES isn't part of ANSI, it isn't considered as a target for autoload, so it needs an explicit `require` as does, say, ASDF.  

If we were to change the policy, I would still like some way to "mark" interfaces as non-ANSI. 

@slids Is the need for an explicit `require` for extensible sequence functionality an onerous burden?

**Comment by alanruttenberg** [comment]
Ok, that's a reasonable principle. Probably not onerous, but perhaps harder
to discover than ideal. I've used that construct before (in other lisps),
and I would have wondered the same thing as @Slids
<https://github.com/Slids>.
One thought is to autoload, but print a warning  (or error, depending on a
switch) that it's not ANSI but loaded as a courtesy, when it's autoloaded.

Alan
