### ISSUE TITLE
Feature request: no quitting on Ctrl+C

### ISSUE THREAD

**Issue by rongcuid** [armedbear/abcl#467]
It would be nice if ABCL do not quit on interruption (Ctrl+C), or EOF (Ctrl-D) for that matter. For instance, in SBCL, Ctrl+C would interrupt the current function only.

**Comment by easye** [comment]
Since ABCL runs on a JVM, that hosting process is responsible for signals.  According to [this five year old StackOverflow post][<https://stackoverflow.com/questions/36858948/regarding-jvm-signal-handling>] there is no standard JDK API for handling signals, so implementing something that would work for all available JVMs is currently not possible.

When run under [SLIME][https://slime.common-lisp.dev/], Emacs handles the CTRL-C in the manner you wish by interrupting the current process so that might be one option for you.  

Closing this request as not possible to implement as far as I know.  Feel free to reopen if someone could suggest an implementation path that hasn't occurred to me.

**Comment by rongcuid** [comment]
I have not tried it, but I found the following resources, in case you find it helpful:

https://stackoverflow.com/questions/19711062/alternative-to-sun-misc-signal
https://github.com/jnr/jnr-posix

Of course, adding more dependencies is not always desired, and a brief look reveals that it might be using `sun.misc` under the hood anyways.

I wonder how SLIME handles it, though...

**Comment by easye** [comment]
> I wonder how SLIME handles it, though...
With SLIME ABCL is running as a sub-process, so Emacs handles the SIGINT generated by CTRL-C  events.

**Comment by rongcuid** [comment]
How does SLIME interrupts ABCL evaluation without killing it? Or does it?

**Comment by easye** [comment]
> How does SLIME interrupts ABCL evaluation without killing it?

SLIME invokes the ABCL `threads:interrupt-thread` function.

**Comment by alanruttenberg** [comment]
No sigint is generated. C-c is just another keystroke binding. If you C-c
in the inferior lisp buffer java quits.
