### ISSUE TITLE
jss sharpsign quote for static field not working

### ISSUE THREAD

**Issue by rongcuid** [armedbear/abcl#475]
Trying the example given from JSS readme:

```
CL-USER(1): #"{java.lang.System}.{fileSeparator}"
#<THREAD "interpreter" {3B1EA186}>: Debugger invoked on condition of type UNBOUND-VARIABLE
  The variable JAVA.LANG.SYSTEM is unbound.
Restarts:
  0: TOP-LEVEL Return to top level.
```

Also, it seems that the `javaparser` dependency is quite ancient. Not sure if it should be bumped.

**Comment by alanruttenberg** [comment]
Long time since I've seen that. I'd forgotten about it. First off, the documentation is wrong. The two{} items are evaluated, and there's no fileSeparator. It's lineSeparator.

```(read-from-string "#\"{System}.{lineSeparator}\"") -> (get-java-field system lineseparator t)```

Use instead  ```#1"System.lineSeparator()"``` or ```#1"System.lineSeparator"```. The latter gives an exception in Java 17 because it is more strict about accessing private variables. But I double checked with ```#1"System.out"```, which gives the expected java.io.PrintStream.

The other thing is #1"" can't take a fully qualified class name. It's ambiguous as to whether it would be a class name or a series of variable accesses. If you get into a situation where you need to disambiguate, try something like this;
```lisp
(jss::with-class-lookup-disambiguated (java.lang) #1"System.lineSeparator()")
```
I guess that should be exported and documented. I'll put in a ticket to remember.

Thanks for the note about javaparser being out of date. I'm not sure when I'll get to updating but I'll put in a ticket for that too.

**Comment by rongcuid** [comment]
But I see this behavior:

```
CL-USER(2): #"System.out"
#<java.io.PrintStream java.io.PrintStream@454e65bc {7C1CF4C2}>
CL-USER(3): #"java.lang.System.out"
#<java.io.PrintStream java.io.PrintStream@454e65bc {5239F022}>
CL-USER(4): #1"System.out"
#<java.io.PrintStream java.io.PrintStream@454e65bc {38CFA4BB}>
CL-USER(5): #1"java.lang.System.out"
#<java.io.PrintStream java.io.PrintStream@454e65bc {E1A559B}>
CL-USER(6): #1"java.lang.System.lineSeparator"
"
"
CL-USER(7): #"java.lang.System.lineSeparator"
"
"
CL-USER(8): #"System.lineSeparator"
"
"
```

What is the difference between `#""` and `#1""`?

**Comment by alanruttenberg** [comment]
Ah, sorry about that. I just checked and see that #1 isn't merged. The older code works that works for your example,  works for field access, but not more complicated expressions. 

What it doesn't work for is #1"System.lineSeparator()" (in my version). Nor does it work for accessing a field of the value of a field. I'll see about whether both can work and merge.

**Comment by alanruttenberg** [comment]
I think for your simple field access, just keep using #"" (no argument). That will keep working  once I merge my version. When merged, with arg 1 you will get the different behavior I described.  Sorry again for the confusion.

**Comment by alanruttenberg** [comment]
Where did you see the documentation that includes #"{java.lang.System}.{fileSeparator}" ?
The current version doesn't have it, and the last commit on that is 2017

**Comment by rongcuid** [comment]
> Where did you see the documentation that includes #"{java.lang.System}.{fileSeparator}" ?
> 
> The current version doesn't have it, and the last commit on that is 2017

`contrib/jss/README.markdown`

**Comment by alanruttenberg** [comment]
Never mind. I'm blind.

**Comment by alanruttenberg** [comment]
https://github.com/armedbear/abcl/pull/479 updates to the what I think is the most recent Javaparser and updates the documentation. Please let me know if you have any other issues.
