### ISSUE TITLE
Building Maxima with ABCL 1.9.0 fails, 1.8.0 works ("FILE-ERROR")

### ISSUE THREAD

**Issue by daute** [armedbear/abcl#494]
Dear ABCL-team,
I build the CAS 'Maxima' (https://sourceforge.net/p/maxima/) regulary using several different Lisp compilers.

One can build it with ABCL 1.8.0 without problems, however the build fails with ABCL 1.9.0 with the error message:
````
Caught FILE-ERROR while processing --eval option "(funcall (intern (symbol-name :operate-on-system) :mk) "maxima" :compile :verbose t)":
  Unable to open #P"/home/dauti/Software/maxima-code/src/numerical/binary-abcl/numerical/f2cl-package.abcl-tmp".
````

I tried to build ABCL from the development source and tried a `git bisect`, which gave me the following commit as problematic:

9c0a9693ea933309e503266255edcde5cc76257c is the first bad commit

Can you take a look on it?
Best regards, Wolfgang

**Comment by easye** [comment]
Thanks for the bug report, and the triage to the change of ABCL's implementation of `compile-file-name`.  

I will try to find time to study in detail who exactly the culprit would be, but given how cross-implementation Maxima strives to be, we will likely have to figure out how to change ABCL rather than patching Maxima. 

More information from my side forthcoming when I get a chance to actually replicate this error locally.

**Comment by alejandrozf** [comment]
I was able to compile and run Maxima with this commit d417a58a

I didn't have time yet to check if this is not introducing regressions to ABCL but a few manual tests worked fine.

**Comment by alejandrozf** [comment]
Update: I fixed my changes, forgot to compare correctly using _pathname-directory_ on the input file too 
The fix is in 6e8dc4f8

**Comment by easye** [comment]
Thanks @alejandrozf!  This will go in for abcl-1.9.1

**Comment by alejandrozf** [comment]
You are welcome ☺️!
