### ISSUE TITLE
ABCL doesn't respect `HOME` env

### ISSUE THREAD

**Issue by catap** [armedbear/abcl#614]
Usually Lisp follow env `HOME` that allow to switch from real home directory to some sandbox where all caches and everything is stored.

For example SBCL:
```
√ ~ % env HOME=/xxx sbcl --eval '(prin1 (user-homedir-pathname))' --non-interactive
This is SBCL 2.3.7, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
#P"/xxx/"
```

Anyway, ABCL works quite differently:
```
√ ~ % env HOME=/xxx abcl --eval '(prin1 (user-homedir-pathname))' --batch          
Armed Bear Common Lisp 1.9.2
Java 11.0.20 MacPorts
OpenJDK 64-Bit Server VM
Low-level initialization completed in 0.179 seconds.
Startup completed in 0.98 seconds.
#P"/Users/catap/"
```

**Comment by easye** [comment]
Since ABCL is hosted on the JVM, it uses the value of the JVM property `user.home` for its implementation of `user-homedir-pathname`.   If you wish to change the runtime value of `user-homedir-pathname`, set that property in the JVM via the `-D` switch 

```
java -jar abcl.jar -Duser.home=/xxx -- --eval '(prin1 (user-homedir-pathname))' --batch    
```

It would not be easy from what I remember to change ABCL to use the value of the HOME variable.  And there would be the question of what the behavior would be under Microsoft Windows OSes.

**Comment by alanruttenberg** [comment]
Why wouldn't it be possible to use ext:getenv in the implementation of user-homedir-pathname?

Not saying it should do that, but curious about the comment that it is hard to do.

**Comment by easye** [comment]
Partly because there isn't a HOME variable in the Windows environment from what I remember.  But mostly because there isn't a requirement from ANSI that `user-homedir-pathname` correspond to HOME, and ABCL has long had the behavior that it corresponds instead to the JVM's notion of `user.home` makes me reluctant to implement a potentially breaking change like this.

**Comment by alanruttenberg** [comment]
Makes sense. Thanks.

**Comment by alanruttenberg** [comment]
You might be able to fix this, for this app only, by adding code to the .abclrc that uses the setenv and chdir functions I wrote some time ago and possibly overriding the function user-homedir-pathname
See https://github.com/alanruttenberg/lsw2/blob/owlapiv4/util/setenv.lisp

**Comment by easye** [comment]
> You might be able to fix this, for this app only, by adding code to the .abclrc that uses the setenv and chdir functions I wrote some time ago and possibly overriding the function user-homedir-pathname 

I added Alan's implementation in abcl-1.9.2, so after loading the `posix-syscalls` contrib, the `uiop:getenv` is rewired to be setf'able.

<https://github.com/armedbear/abcl/commit/37d999f8ded0a8ece34ef142813a2c2a8334bdbb>
