### ISSUE TITLE
The symbol "MAKE-THREAD-LOCK" was not found in package EXT.

### ISSUE THREAD

**Issue by catap** [armedbear/abcl#616]
Long story short: some lisp packages can't be load into ABCL. At least `cl-base64` and `kmrcl`.

The error looks like:
```
 Caught READER-ERROR while processing --eval option "(asdf:operate (quote asdf:build-op) (quote kmrcl))":
   The symbol "MAKE-THREAD-LOCK" was not found in package EXT.
```

I can reproduce it on my machine via `(asdf:operate (quote asdf:build-op) (quote kmrcl))`.

**Comment by easye** [comment]
As far as I can tell these are problems with these systems, not ABCL:  the `make-thread-lock` symbol has been part of the `threads` package since at least abcl-0.16.0 released way back in 06-SEP-2009.  It may have been in the `external` package for a deprecation period, but that is long since passed. 

Please file tickets with the maintainers of these systems to fix their code.

**Comment by catap** [comment]
Unfortently it is quite old lisp systems, I guess more than 15 years old. Ok, I'll make a report as soon as figure out who is supporting it these days.

Thanks!

**Comment by catap** [comment]
Ok, the root cause is: http://git.kpe.io/?p=kmrcl.git;a=blob;f=processes.lisp;h=7bdf018e6084324dec584bc1c104e613950928f4;hb=HEAD#l31

**Comment by catap** [comment]
BTW `#+sbcl (ext:make-thread-lock)` seems quite useful and I not sure that removing it is good idea.

Special that existed lisp code may not be supported.
