### ISSUE TITLE
Current release - 1.9.2 or 1.9.3?

### ISSUE THREAD

**Issue by daute** [armedbear/abcl#681]
Dear ABCL-team,
on https://abcl.org/releases/ there is - since 2024-09-02 - a release 1.9.3, on https://abcl.org/ 1.9.2 is promoted as current release. Should that be considered as a release candidate, pre-release, or something similar? Or was just the website not updated?
And is there somewhere a changelog?

Best regards, Wolfgang

(And on https://abcl.org/releases/ there is also a directory 'current', which contains an older release.)

**Comment by easye** [comment]
The official current release is 1.9.2.  The binaries present under <https//abcl.org/releases/1.9.3/> are release candidates for the long overdue 1.9.3, but they don't have associated cryptographic signatures which is how one can tell that an official release has not been completed.

See a <https://github.com/armedbear/abcl/blob/14bc85e09bd51cc3bc7cd0c522ecc98f841eb09c/CHANGES> a more or less complete summary features and fixed bugs present in 1.9.3. 

Releasing 1.9.3 has been held up for: 

1.  Maintainer fatigue as I have unfortunately been otherwise out-of-action, busy, and occupied
2.  Problems with CFFI under arm64 that while not a regression (the problems are also present in 1.9.2), are highly annoying and mysterious enough for me to want to fix it for 1.9.3, particularly as they seem to vary by openjdk version, which might indicate some deeper problem.  Note that it is not evident that fixing these problems involves changes to ABCL, as perhaps we only need to patch the ABCL-specific parts in CFFI.  

Again, apologies for the confusion but thanks for the question:  it has prodded me to start thinking  about releasing 1.9.3 again.

**Comment by daute** [comment]
Thanks for the fast answer.
Best regards, Wolfgang
