### ISSUE TITLE
How is `dump-classpath` expected to function?

### ISSUE THREAD

**Issue by rpgoldman** [armedbear/abcl#689]
I am looking at some old code I am trying to resurrect, and I see code that loops over the list returned by `java:dump-classpath` and expecting that the elements will be ... alists? ... with pathnames in them:

``` lisp
(find *my-jar-name*
      (loop for x in (dump-classpath)
            appending (remove-if-not 'pathnamep (rest x)))
      :test 'equalp :key 'pathname-name)
```

When I look at the return value from `java:dump-classpath` running ABCL 1.9.2 in JDK 23, I see a list of Java objects, instead, causing a type error in the above code:

```
CL-USER(1): (java:dump-classpath)
(#<jdk.internal.loader.ClassLoaders$AppClassLoader jdk.internal.loader.ClassLoaders.... {68835DBD}> #<jdk.internal.loader.ClassLoaders$PlatformClassLoader jdk.internal.loader.ClassLoaders.... {4967B218}>)
```

Am I doing something wrong here? Or is this some change in Java that I just need to adapt myself to?

AFAICT, there is no documentation for `java:dump-classpath` in the manual. Apologies if I have overlooked something.

**Comment by rpgoldman** [comment]
Probably it would be better for me to say what I am really trying to do:

I have a large application (in this case the PRISM model checker).  I have some functions in CL that I wish to make available to the model checker. I have a class to do this `ABCLHeuristicEngine`.

So `ABCLHeuristicEngine` creates an ABCL `Interpreter`.  I wish to load into this interpreter a JAR file that is in the running PRISM's `classpath`.  I used to be able to do this by groveling over the classpath, using `dump-classpath`, finding the JAR file I wanted, and loading that with `(asdf-jar:add-to-asdf <jarfile>)`.  Because of the change in `dump-classpath`, I am no longer able to find the JAR file to load. This is probably a good thing from the standpoint of Java security, but it's really hurting me!  Is there some way I can tell this class where to find the JAR file in question?

I guess a crude way to do this is to put the JAR file's pathname into an environment variable, and then read it out again in `ABCLHeuristicEngine`.  Is there something less kludgy I could do?

**Comment by easye** [comment]
The implementation of `java:dump-classpath` hasn't changed:  it still thunks down to returning the `java:java-object` wrapped value of [java.lang.Class.getClassLoader](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getClassLoader-->).  What *has* changed is that since openjdk9, the JVM no longer uses JAR files for its internal packaging.  What you are seeing are the `java-object` wrapped members of the classloaders, which no longer includes additional JAR files taken from the CLASSPATH environment variable.  Instead, the runtime setting is now present in the `java.class.path` system property.

Apparently when I ported ABCL to post-openjdk9 environments, I noticed this difference, and implemented `system:java.class.path` which should do what you want.  If you are indeed distributing ASDF definitions in `asdf-jar` artifacts specified on the CLASSPATH, you can grovel the runtime path via this function.  

I take it you are distributing your PRISM add-ons to a community that doesn't really want to know anything about CL, so telling them to ensure that the ASDF jar artifacts in the CLASSPATH is an easy to understand instruction?  If not, just configuring ASDF directly to find its systems on the local filesystem might be a little more flexible.

**Comment by easye** [comment]
Hmm, the [implementation of `sys:java.class.path`](https://github.com/armedbear/abcl/blob/master/src/org/armedbear/lisp/abcl-contrib.lisp#L101) is definitely coded a little wonkily.  It returns two values, the first being a list of `cl:pathname` references containing directories of its components, and the second being the string value of the components.   The reason for this weird implementation lies in its use within the implementation to search the CLASSPATH for the `abcl.jar` in order to find the `abcl-contrib.jar` artifact.  This explains why this function is in the `system` package and not the `extensions` as it is was just considered for "internal" use.   Long-term the plan is to have all these sort of routines in `ext`, but don't worry about stability as I usually ensure that the symbol is exported from `sys` as well.

If you want to do your own parsing, just introspect the value of `java.class.path` directly via: 

``` 
(java:jstatic "getProperty" "java.lang.System" "java.class.path")
```
