### ISSUE TITLE
Advertise that Github issues list is a valid place to report ABCL bugs

### ISSUE THREAD

**Issue by alanruttenberg** [armedbear/abcl#83]
@robert-dodier says that he wasn't able to find this issues list by looking at the common-lisp.net project info, and that he only found Trac.

**Comment by easye** [comment]
Trac is the master location for information on ABCL issues for me, as it contains more than a decades worth of issue reporting.  That there isn't currently a good mechanism to get a open login is definitely a problem.  That github.com/armedbear/abcl and common-lisp.net/abcl/abcl also have inconsistent issues is also a problem

I would like to have a more comprehensive system in place, but simply haven't had the time to do the necessary engineering.

**Comment by robert-dodier** [comment]
Hi, thanks for thinking about this issue. Let me know at this point that the project page https://common-lisp.net/project/armedbear/ has 2 links related to bugs. One is labeled "Bug reporting" and it leads to https://common-lisp.net/project/armedbear/bugreporting.shtml, which says the bugs should be reported to the armedbear-devel mailing list. The other is labeled "Bug tracker" and leads to https://abcl.org/trac/report/1 . 

Without changing the bug reporting mechanisms at all, I think it could help if the different links were just clarified a little. In the case of the bug tracker, maybe put a note on the link to say that Trac is readl-only for non-developers or something like that, and to say that non-developers reporting bugs should use the "Bug reporting" link. In the case of "Bug reporting", maybe redirect attention to this issues tracker instead of the mailing list.

Thanks for your efforts, I do appreciate it.

**Comment by easye** [comment]
Please post about the Bear wherever you find most convenient.
